#!/bin/bash
if [ -d "/run/systemd/system/" ]; then
  pkill -f input-remapper-service  # might have been started by the gui previously
  systemctl enable input-remapper
  systemctl start input-remapper
fi
